/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

/**
 *
 * @author s.lucas
 */
public class FolhadePag extends javax.swing.JFrame {

    /**
     * Creates new form FolhadePag
     */
    public FolhadePag() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbRTítulo = new javax.swing.JLabel();
        lbRNome = new javax.swing.JLabel();
        lbResNome = new javax.swing.JLabel();
        lbRQHoras = new javax.swing.JLabel();
        lbResQHoras = new javax.swing.JLabel();
        lbRSBruto = new javax.swing.JLabel();
        lbResSalBruto = new javax.swing.JLabel();
        lbDINSS = new javax.swing.JLabel();
        lbRDINSS = new javax.swing.JLabel();
        lbDIR = new javax.swing.JLabel();
        lbRDIR = new javax.swing.JLabel();
        lbRQHExtra = new javax.swing.JLabel();
        lbResQHExtras = new javax.swing.JLabel();
        lbRVHExtras = new javax.swing.JLabel();
        lbResVHExtras = new javax.swing.JLabel();
        lbRVSFam = new javax.swing.JLabel();
        lbResVSFam = new javax.swing.JLabel();
        lbRSLíq = new javax.swing.JLabel();
        lbResSalLiq = new javax.swing.JLabel();
        lbTítulo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbQHoras = new javax.swing.JLabel();
        txtQHoras = new javax.swing.JTextField();
        lbVHora = new javax.swing.JLabel();
        txtVHora = new javax.swing.JTextField();
        lbQFilhos = new javax.swing.JLabel();
        txtQFilhos = new javax.swing.JTextField();
        lbQHExtras = new javax.swing.JLabel();
        txtQHExtras = new javax.swing.JTextField();
        btGerarFolha = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jLabel20.setText("jLabel20");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbRTítulo.setText("HOLERITE - MAIO/2023");

        lbRNome.setText("Funcionário:");

        lbResNome.setText("???");

        lbRQHoras.setText("Quant. Horas:");

        lbResQHoras.setText("???");

        lbRSBruto.setText("Salário Bruto:");

        lbResSalBruto.setText("???");

        lbDINSS.setText("Desconto INSS:");

        lbRDINSS.setText("???");

        lbDIR.setText("Desconto IR:");

        lbRDIR.setText("???");

        lbRQHExtra.setText("Quant. Horas Extras:");

        lbResQHExtras.setText("???");

        lbRVHExtras.setText("Valor Horas Extras:");

        lbResVHExtras.setText("???");

        lbRVSFam.setText("Valor Sál. Fam.:");

        lbResVSFam.setText("???");

        lbRSLíq.setText("Salário Líquido:");

        lbResSalLiq.setText("R$???");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbDIR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbRDIR))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbDINSS)
                                    .addComponent(lbRSBruto)
                                    .addComponent(lbRQHoras)
                                    .addComponent(lbRNome))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbResNome)
                                    .addComponent(lbResQHoras)
                                    .addComponent(lbResSalBruto)
                                    .addComponent(lbRDINSS))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbRSLíq)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbResSalLiq))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbRVSFam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbResVSFam))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbRVHExtras)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbResVHExtras))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbRQHExtra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbResQHExtras))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lbRTítulo)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbRTítulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRNome)
                    .addComponent(lbResNome)
                    .addComponent(lbRQHExtra)
                    .addComponent(lbResQHExtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRQHoras)
                    .addComponent(lbResQHoras)
                    .addComponent(lbRVHExtras)
                    .addComponent(lbResVHExtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRSBruto)
                    .addComponent(lbResSalBruto)
                    .addComponent(lbRVSFam)
                    .addComponent(lbResVSFam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDINSS)
                    .addComponent(lbRDINSS)
                    .addComponent(lbRSLíq)
                    .addComponent(lbResSalLiq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDIR)
                    .addComponent(lbRDIR))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        lbTítulo.setText("FOLHA DE PAGAMENTO");

        lbNome.setText("Funcionário (Nome):");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lbQHoras.setText("Quant. Horas:");

        lbVHora.setText("Valor Hora:");

        lbQFilhos.setText("Quant. Filhos:");

        lbQHExtras.setText("Quant. Horas extras:");

        btGerarFolha.setText("Gerar Folha");
        btGerarFolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarFolhaActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(txtNome)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(lbTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbNome))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbQHoras)
                            .addComponent(txtQHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbVHora)
                            .addComponent(txtVHora, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbQFilhos)
                                    .addComponent(txtQFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btGerarFolha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbQHExtras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQHExtras)
                            .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQHoras)
                    .addComponent(lbVHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQFilhos)
                    .addComponent(lbQHExtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQHExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(btGerarFolha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btGerarFolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarFolhaActionPerformed
        String nome;
        double qHoras, qFilhos, vHora, qHorExtra, salBruto, salHorExtras, salFam, descINSS, descIR, salLiq;
        
        nome = txtNome.getText();
        qHoras = Double.parseDouble(txtQHoras.getText());
        qFilhos = Double.parseDouble(txtQFilhos.getText());
        vHora = Double.parseDouble(txtVHora.getText());
        qHorExtra = Double.parseDouble(txtQHExtras.getText());
        //processamento
        salBruto = qHoras*vHora;
        salHorExtras = qHorExtra*vHora*1.5;
        salFam = qFilhos*15;
        descINSS = 0;
        if(salBruto<=1320){
            descINSS = salBruto*0.075;
        }else if(salBruto>1320&&salBruto<=2571.29){
            descINSS = salBruto*0.09;
        }else if(salBruto>2571.29&&salBruto<=3856.94){
            descINSS = salBruto*0.012;
        }else{
            descINSS = salBruto*0.014;
        }
        descIR = 0;
        if(salBruto<1903.09){
            descIR = salBruto*0;
        }else if(salBruto>=1903.09&&salBruto<=2826.65){
            descIR = salBruto*0.075;
        }else if(salBruto>2826.65&&salBruto<=3751.05){
            descIR = salBruto*0.15;
        }else if(salBruto>3751.05&&salBruto<=4664.68){
            descIR = salBruto*0.225;
        }else{
            descIR = salBruto*0.275;
        }
        salLiq = salBruto+salFam+salHorExtras-descINSS-descIR;
        lbResNome.setText(nome);
        lbResQHoras.setText(String.valueOf(qHoras));
        
        lbResSalBruto.setText(String.valueOf(salBruto));
        lbRDINSS.setText(String.valueOf(descINSS));
        lbRDIR.setText(String.valueOf(descIR));
        lbResQHExtras.setText(String.valueOf(qHorExtra));
        lbResVHExtras.setText(String.valueOf(salHorExtras));
        lbResVSFam.setText(String.valueOf(salFam));
        lbResSalLiq.setText(String.valueOf(salLiq));
    }//GEN-LAST:event_btGerarFolhaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtNome.setText(null);
        txtQHoras.setText(null);
        txtVHora.setText(null);
        txtQFilhos.setText(null);
        txtQHExtras.setText(null);
        lbResNome.setText("???");
        lbResQHoras.setText("???");
        lbResSalBruto.setText("???");
        lbRDINSS.setText("???");
        lbRDIR.setText("???");
        lbResQHExtras.setText("???");
        lbResVHExtras.setText("???");
        lbResVSFam.setText("???");
        lbResSalLiq.setText("R$???");
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FolhadePag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FolhadePag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FolhadePag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FolhadePag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FolhadePag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerarFolha;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDINSS;
    private javax.swing.JLabel lbDIR;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbQFilhos;
    private javax.swing.JLabel lbQHExtras;
    private javax.swing.JLabel lbQHoras;
    private javax.swing.JLabel lbRDINSS;
    private javax.swing.JLabel lbRDIR;
    private javax.swing.JLabel lbRNome;
    private javax.swing.JLabel lbRQHExtra;
    private javax.swing.JLabel lbRQHoras;
    private javax.swing.JLabel lbRSBruto;
    private javax.swing.JLabel lbRSLíq;
    private javax.swing.JLabel lbRTítulo;
    private javax.swing.JLabel lbRVHExtras;
    private javax.swing.JLabel lbRVSFam;
    private javax.swing.JLabel lbResNome;
    private javax.swing.JLabel lbResQHExtras;
    private javax.swing.JLabel lbResQHoras;
    private javax.swing.JLabel lbResSalBruto;
    private javax.swing.JLabel lbResSalLiq;
    private javax.swing.JLabel lbResVHExtras;
    private javax.swing.JLabel lbResVSFam;
    private javax.swing.JLabel lbTítulo;
    private javax.swing.JLabel lbVHora;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQFilhos;
    private javax.swing.JTextField txtQHExtras;
    private javax.swing.JTextField txtQHoras;
    private javax.swing.JTextField txtVHora;
    // End of variables declaration//GEN-END:variables
}
